/* 
 * $Header:$ 
 * 
 * Copyright (c) ${YEAR} FXCM, LLC. 
 * 55 Water Street, 50th Floor 10041
 * 
 * THIS SOFTWARE IS THE CONFIDENTIAL AND PROPRIETARY INFORMATION OF 
 * FXCM, LLC. ("CONFIDENTIAL INFORMATION"). YOU SHALL NOT DISCLOSE 
 * SUCH CONFIDENTIAL INFORMATION AND SHALL USE IT ONLY IN ACCORDANCE 
 * WITH THE TERMS OF THE LICENSE AGREEMENT YOU ENTERED INTO WITH 
 * FXCM. 
 *
 * Author:  Andre Mermegas
 * Created: ${DATE} ${TIME}
 * 
 * $History: $ 
 */
